In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(f"arr1: {arr1}, datatype: {type(arr1)}")

arr1: [1 2 3 4], datatype: <class 'numpy.ndarray'>


In [4]:
ar_list = [1,2,3,4]
print(f"ar_list: {ar_list}, datatype: {type(ar_list)}")

ar_list: [1, 2, 3, 4], datatype: <class 'list'>


In [5]:
vector = np.array([1,2,3])
print('vector :',vector)

vector : [1 2 3]


In [6]:
matrix=np.array([[1,2,3],[4,5,6]])
print('matrix',matrix)

matrix [[1 2 3]
 [4 5 6]]


In [9]:
tensor=np.array([[[1,2,44],[3,4,55]],
         [[5,6,66],[7,8,77]]])
print('tensor',tensor)

tensor [[[ 1  2 44]
  [ 3  4 55]]

 [[ 5  6 66]
  [ 7  8 77]]]


In [10]:
print(tensor.shape)
print(tensor.size)

(2, 2, 3)
12


In [11]:
tensor.ndim

3